# CMake generated Testfile for 
# Source directory: C:/Users/vande/Desktop/NETWORK
# Build directory: C:/Users/vande/Desktop/NETWORK/build-msvc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(primitive "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_primitive.exe")
  set_tests_properties(primitive PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(primitive "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_primitive.exe")
  set_tests_properties(primitive PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(primitive "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_primitive.exe")
  set_tests_properties(primitive PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(primitive "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_primitive.exe")
  set_tests_properties(primitive PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(primitive NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(graph "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_graph.exe")
  set_tests_properties(graph PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(graph "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_graph.exe")
  set_tests_properties(graph PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(graph "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_graph.exe")
  set_tests_properties(graph PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(graph "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_graph.exe")
  set_tests_properties(graph PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(graph NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(topology "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_topology.exe")
  set_tests_properties(topology PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(topology "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_topology.exe")
  set_tests_properties(topology PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(topology "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_topology.exe")
  set_tests_properties(topology PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(topology "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_topology.exe")
  set_tests_properties(topology PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(topology NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(determinism "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_determinism.exe")
  set_tests_properties(determinism PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(determinism "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_determinism.exe")
  set_tests_properties(determinism PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(determinism "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_determinism.exe")
  set_tests_properties(determinism PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(determinism "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_determinism.exe")
  set_tests_properties(determinism PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(determinism NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(expressivity "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_expressivity.exe")
  set_tests_properties(expressivity PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(expressivity "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_expressivity.exe")
  set_tests_properties(expressivity PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(expressivity "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_expressivity.exe")
  set_tests_properties(expressivity PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(expressivity "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_expressivity.exe")
  set_tests_properties(expressivity PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(expressivity NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(expressivity_regression "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_expressivity_regression.exe")
  set_tests_properties(expressivity_regression PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(expressivity_regression "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_expressivity_regression.exe")
  set_tests_properties(expressivity_regression PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(expressivity_regression "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_expressivity_regression.exe")
  set_tests_properties(expressivity_regression PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(expressivity_regression "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_expressivity_regression.exe")
  set_tests_properties(expressivity_regression PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(expressivity_regression NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fsm "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_fsm.exe")
  set_tests_properties(fsm PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fsm "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_fsm.exe")
  set_tests_properties(fsm PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(fsm "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_fsm.exe")
  set_tests_properties(fsm PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(fsm "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_fsm.exe")
  set_tests_properties(fsm PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(fsm NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(generated "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_generated.exe")
  set_tests_properties(generated PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(generated "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_generated.exe")
  set_tests_properties(generated PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(generated "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_generated.exe")
  set_tests_properties(generated PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(generated "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_generated.exe")
  set_tests_properties(generated PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(generated NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(serialization "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_serialization.exe")
  set_tests_properties(serialization PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(serialization "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_serialization.exe")
  set_tests_properties(serialization PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(serialization "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_serialization.exe")
  set_tests_properties(serialization PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(serialization "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_serialization.exe")
  set_tests_properties(serialization PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(serialization NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(analysis "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_analysis.exe")
  set_tests_properties(analysis PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(analysis "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_analysis.exe")
  set_tests_properties(analysis PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(analysis "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_analysis.exe")
  set_tests_properties(analysis PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(analysis "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_analysis.exe")
  set_tests_properties(analysis PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(analysis NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(retry "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_retry.exe")
  set_tests_properties(retry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(retry "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_retry.exe")
  set_tests_properties(retry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(retry "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_retry.exe")
  set_tests_properties(retry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(retry "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_retry.exe")
  set_tests_properties(retry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(retry NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(freeze "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_freeze.exe")
  set_tests_properties(freeze PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(freeze "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_freeze.exe")
  set_tests_properties(freeze PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(freeze "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_freeze.exe")
  set_tests_properties(freeze PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(freeze "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_freeze.exe")
  set_tests_properties(freeze PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(freeze NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cross_toolchain "C:/Users/vande/Desktop/NETWORK/build-msvc/Debug/test_cross_toolchain.exe")
  set_tests_properties(cross_toolchain PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cross_toolchain "C:/Users/vande/Desktop/NETWORK/build-msvc/Release/test_cross_toolchain.exe")
  set_tests_properties(cross_toolchain PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cross_toolchain "C:/Users/vande/Desktop/NETWORK/build-msvc/MinSizeRel/test_cross_toolchain.exe")
  set_tests_properties(cross_toolchain PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cross_toolchain "C:/Users/vande/Desktop/NETWORK/build-msvc/RelWithDebInfo/test_cross_toolchain.exe")
  set_tests_properties(cross_toolchain PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;25;add_test;C:/Users/vande/Desktop/NETWORK/CMakeLists.txt;0;")
else()
  add_test(cross_toolchain NOT_AVAILABLE)
endif()
