#include "test_support.h"
#include "nexum_builder.h"
#include "nexum_config.h"

static nexum_builder_capacities_t caps(uint32_t value){return(nexum_builder_capacities_t){value,value,value,value,value};}
static int config_helpers(void){pnp_config_t c=pass_config(0u),before;CHECK(nexum_cell_set_alu(&c,PNP_ALU_ADD,nexum_source_state(0u),nexum_source_one())==PNP_OK);CHECK(nexum_cell_set_predicate(&c,PNP_PRED_EQ,nexum_source_constant(2u),0u,0u)==PNP_OK);CHECK(nexum_cell_set_state_update(&c,PNP_UPDATE_RESULT,0u,0u,0u)==PNP_OK);CHECK(nexum_cell_set_event_update(&c,PNP_EVENT_DEST_METADATA,PNP_EVENT_VALUE_RESULT,1u,0u,0u)==PNP_OK);CHECK(nexum_cell_set_emit(&c,1u,2u)==PNP_OK);CHECK(nexum_cell_config_validate(&c)==PNP_OK);before=c;CHECK(nexum_cell_set_alu(&c,PNP_ALU_COUNT,nexum_source_zero(),nexum_source_zero())==PNP_ERR_INVALID_CONFIG);CHECK(memcmp(&c,&before,sizeof(c))==0);CHECK(nexum_cell_set_predicate(&c,PNP_PRED_COUNT,nexum_source_zero(),0u,0u)==PNP_ERR_INVALID_CONFIG);CHECK(memcmp(&c,&before,sizeof(c))==0);return 0;}
static int successful(void){nexum_program_t p;nexum_builder_t b;nexum_domain_ref_t d;nexum_cell_ref_t a,z;uint32_t in,out;pnp_config_t c;CHECK(nexum_builder_init(&b,&p,caps(2u))==PNP_OK);CHECK(nexum_builder_add_state_domain(&b,NULL,&d)==PNP_OK&&d==0u);nexum_cell_config_init(&c);c.emit_true=1u;CHECK(nexum_builder_add_cell(&b,&c,d,&a)==PNP_OK&&a==0u);CHECK(nexum_builder_add_cell(&b,&c,d,&z)==PNP_OK&&z==1u);CHECK(nexum_builder_connect(&b,a,0u,z,0u)==PNP_OK);CHECK(nexum_builder_bind_output(&b,a,0u,&out)==PNP_OK&&p.outputs[0].route_order==1u);CHECK(nexum_builder_bind_input(&b,a,0u,&in)==PNP_OK);CHECK(nexum_builder_finalize(&b)==PNP_OK);CHECK(nexum_program_validate(&p)==PNP_OK);CHECK(nexum_builder_finalize(&b)==PNP_ERR_INVALID_ARGUMENT);CHECK(nexum_builder_connect(&b,a,0u,z,0u)==PNP_ERR_INVALID_ARGUMENT);return 0;}
static int exhaust_one(int kind){nexum_program_t p;nexum_builder_t b;pnp_config_t c;nexum_domain_ref_t d; nexum_cell_ref_t a,z;uint32_t id;pnp_result_t r;nexum_builder_capacities_t cp=caps(2u);if(kind==0)cp.cells=1u;if(kind==1)cp.edges=0u;if(kind==2)cp.state_domains=0u;if(kind==3)cp.inputs=0u;if(kind==4)cp.outputs=0u;CHECK(nexum_builder_init(&b,&p,cp)==PNP_OK);if(kind==2){CHECK(nexum_builder_add_state_domain(&b,NULL,&d)==PNP_ERR_BUFFER_FULL);return 0;}CHECK(nexum_builder_add_state_domain(&b,NULL,&d)==PNP_OK);nexum_cell_config_init(&c);c.emit_true=1u;CHECK(nexum_builder_add_cell(&b,&c,d,&a)==PNP_OK);if(kind==0){CHECK(nexum_builder_add_cell(&b,&c,d,&z)==PNP_ERR_BUFFER_FULL);return 0;}CHECK(nexum_builder_add_cell(&b,&c,d,&z)==PNP_OK);if(kind==1)r=nexum_builder_connect(&b,a,0u,z,0u);else if(kind==3)r=nexum_builder_bind_input(&b,a,0u,&id);else r=nexum_builder_bind_output(&b,a,0u,&id);CHECK(r==PNP_ERR_BUFFER_FULL);CHECK(b.error==PNP_ERR_BUFFER_FULL);CHECK(nexum_builder_finalize(&b)==PNP_ERR_BUFFER_FULL);return 0;}
static int failures(void){nexum_program_t p;nexum_builder_t b;pnp_config_t c;nexum_domain_ref_t d;nexum_cell_ref_t cell;for(int i=0;i<5;++i)CHECK(exhaust_one(i)==0);CHECK(nexum_builder_init(&b,&p,caps(2u))==PNP_OK);CHECK(nexum_builder_add_state_domain(&b,NULL,&d)==PNP_OK);nexum_cell_config_init(&c);c.alu_op=(uint8_t)PNP_ALU_COUNT;CHECK(nexum_builder_add_cell(&b,&c,d,&cell)==PNP_ERR_INVALID_CONFIG);CHECK(p.cell_count==0u);CHECK(nexum_builder_init(&b,&p,caps(2u))==PNP_OK);nexum_cell_config_init(&c);CHECK(nexum_builder_add_cell(&b,&c,99u,&cell)==PNP_ERR_INVALID_CONFIG);CHECK(nexum_builder_init(&b,&p,caps(2u))==PNP_OK);CHECK(nexum_builder_add_state_domain(&b,NULL,&d)==PNP_OK);c.emit_true=1u;CHECK(nexum_builder_add_cell(&b,&c,d,&cell)==PNP_OK);CHECK(nexum_builder_connect(&b,cell,PNP_MAX_OUTPUTS,cell,0u)==PNP_ERR_INVALID_GRAPH);CHECK(nexum_builder_init(&b,&p,caps(2u))==PNP_OK);p.reserved[0]=1u;CHECK(nexum_builder_finalize(&b)==PNP_ERR_INVALID_GRAPH);return 0;}
int main(void){CHECK(config_helpers()==0);CHECK(successful()==0);CHECK(failures()==0);return 0;}
