#include "test_support.h"
#include "nexum_compile.h"

static nexum_compile_spec_t spec(nexum_behavior_t behavior){nexum_compile_spec_t s;memset(&s,0,sizeof(s));s.behavior=(uint8_t)behavior;s.data_type=1u;s.time_type=2u;s.ack_type=3u;s.retry_type=4u;s.failure_type=5u;s.retry_limit=3u;return s;}
static int compile_one(nexum_behavior_t behavior,nexum_program_t *p){nexum_compile_spec_t s=spec(behavior);nexum_compile_requirements_t r;CHECK(nexum_compile_requirements(&s,&r)==PNP_OK&&r.exact==1u);CHECK(nexum_compile(&s,r.capacities,p)==PNP_OK);return 0;}
static int fundamentals(void){nexum_program_t p;for(uint32_t i=0u;i<(uint32_t)NEXUM_BEHAVIOR_COUNT;++i){CHECK(compile_one((nexum_behavior_t)i,&p)==0);CHECK(nexum_program_validate(&p)==PNP_OK);}return 0;}
static void manual_single(nexum_behavior_t behavior,nexum_program_t *p){pnp_config_t c=pass_config(1u);memset(p,0,sizeof(*p));if(behavior==NEXUM_BEHAVIOR_CONDITIONAL_ROUTE){c.source_a.kind=(uint8_t)PNP_SRC_EVENT_FIELD;c.predicate=(uint8_t)PNP_PRED_EQ;c.compare_source.kind=(uint8_t)PNP_SRC_CONSTANT;c.emit_false=2u;}else if(behavior==NEXUM_BEHAVIOR_COUNTER){c.source_a.kind=(uint8_t)PNP_SRC_STATE_WORD;c.source_b.kind=(uint8_t)PNP_SRC_ONE;c.alu_op=(uint8_t)PNP_ALU_ADD;c.update_mode=(uint8_t)PNP_UPDATE_RESULT;}else if(behavior==NEXUM_BEHAVIOR_ACK){c.event_update_destination=(uint8_t)PNP_EVENT_DEST_TYPE;c.event_update_source=(uint8_t)PNP_EVENT_VALUE_CONSTANT;}p->cell_count=1u;p->state_domain_count=1u;p->input_count=1u;p->output_count=behavior==NEXUM_BEHAVIOR_CONDITIONAL_ROUTE?2u:1u;p->cells[0]=(nexum_cell_t){0u,0u,c};p->inputs[0]=(nexum_input_t){0u,0u,0u,0u};p->outputs[0]=(nexum_output_t){0u,0u,0u,0u};if(p->output_count==2u)p->outputs[1]=(nexum_output_t){1u,0u,1u,0u};}
static int manual_vs_compiler(void){const nexum_behavior_t kinds[]={NEXUM_BEHAVIOR_PASS,NEXUM_BEHAVIOR_CONDITIONAL_ROUTE,NEXUM_BEHAVIOR_COUNTER,NEXUM_BEHAVIOR_ACK};for(uint32_t i=0u;i<4u;++i){nexum_compile_spec_t s=spec(kinds[i]);nexum_compile_requirements_t r;nexum_program_t expected,actual;manual_single(kinds[i],&expected);CHECK(nexum_program_finalize(&expected)==PNP_OK);CHECK(nexum_compile_requirements(&s,&r)==PNP_OK);CHECK(nexum_compile(&s,r.capacities,&actual)==PNP_OK);CHECK(memcmp(&expected,&actual,sizeof(expected))==0);}return 0;}
static int deterministic(void){nexum_compile_spec_t s=spec(NEXUM_BEHAVIOR_RETRY);nexum_compile_requirements_t r;nexum_program_t reference,current;CHECK(nexum_compile_requirements(&s,&r)==PNP_OK);CHECK(nexum_compile(&s,r.capacities,&reference)==PNP_OK);for(uint32_t i=0u;i<10000u;++i){CHECK(nexum_compile(&s,r.capacities,&current)==PNP_OK);CHECK(memcmp(&reference,&current,sizeof(reference))==0);}r.capacities.edges--;CHECK(nexum_compile(&s,r.capacities,&current)==PNP_ERR_BUFFER_FULL);return 0;}
typedef struct run_fixture{pnp_node_t nodes[16];pnp_edge_t edges[32];pnp_state_domain_t domains[2];pnp_graph_t graph;pnp_graph_event_t qi[32];pnp_queue_t q;pnp_graph_output_t oi[32];pnp_graph_output_buffer_t out;pnp_run_stats_t stats;}run_fixture_t;
static int lower_program(const nexum_program_t *p,run_fixture_t *f){nexum_runtime_storage_t st={f->nodes,16u,f->edges,32u,f->domains,2u};memset(f,0,sizeof(*f));st.nodes=f->nodes;st.edges=f->edges;st.state_domains=f->domains;CHECK(nexum_program_lower(p,&st,&f->graph)==PNP_OK);f->out=(pnp_graph_output_buffer_t){f->oi,32u,0u};return 0;}
static int run_event(run_fixture_t *f,const nexum_program_t *p,uint32_t type,uint64_t seq){pnp_event_t e={0};e.type=type;e.sequence=seq;pnp_queue_init(&f->q,f->qi,32u);CHECK(nexum_program_inject(p,&f->q,0u,&e)==PNP_OK);CHECK(pnp_graph_run(&f->graph,&f->q,&f->out,(pnp_run_limits_t){32u,32u},&f->stats)==PNP_OK);return 0;}
static int retry_equivalence(void){nexum_compile_spec_t s=spec(NEXUM_BEHAVIOR_RETRY);nexum_compile_requirements_t req;nexum_program_t p;run_fixture_t f;CHECK(nexum_compile_requirements(&s,&req)==PNP_OK);CHECK(nexum_compile(&s,req.capacities,&p)==PNP_OK);CHECK(lower_program(&p,&f)==0);CHECK(run_event(&f,&p,1u,7u)==0);CHECK(f.domains[0].state.words[1]==1u);CHECK(run_event(&f,&p,3u,6u)==0);CHECK(f.domains[0].state.words[1]==1u);CHECK(run_event(&f,&p,2u,0u)==0);CHECK(f.oi[f.out.count-1u].event.sequence==7u);CHECK(run_event(&f,&p,3u,7u)==0);CHECK(f.domains[0].state.words[1]==0u);CHECK(run_event(&f,&p,1u,9u)==0);for(uint32_t i=0u;i<4u;++i)CHECK(run_event(&f,&p,2u,0u)==0);CHECK(f.domains[0].state.words[1]==0u);{uint32_t count=f.out.count;CHECK(run_event(&f,&p,2u,0u)==0);CHECK(f.out.count==count);}return 0;}
int main(void){CHECK(fundamentals()==0);CHECK(manual_vs_compiler()==0);CHECK(deterministic()==0);CHECK(retry_equivalence()==0);return 0;}
