#include "test_support.h"

static int branch_and_diamond(void){
    pnp_node_t n[4];pnp_state_domain_t d[4];pnp_edge_t e[6];pnp_graph_event_t store[16];pnp_queue_t q;pnp_graph_output_t items[8];pnp_graph_output_buffer_t out={items,8u,0u};pnp_run_stats_t stats;pnp_event_t input={0};pnp_graph_t g={n,4u,4u,e,6u,6u,d,4u,4u};memset(n,0,sizeof(n));memset(d,0,sizeof(d));for(uint32_t i=0u;i<4u;++i){n[i].config=pass_config(1u);n[i].state_domain=i;}n[0].config.emit_true=3u;e[0]=(pnp_edge_t){0u,0u,1u,10u};e[1]=(pnp_edge_t){0u,1u,2u,20u};e[2]=(pnp_edge_t){1u,0u,3u,30u};e[3]=(pnp_edge_t){2u,0u,3u,40u};e[4]=(pnp_edge_t){3u,0u,PNP_EXTERNAL_NODE,0u};e[5]=(pnp_edge_t){3u,0u,PNP_EXTERNAL_NODE,1u};pnp_queue_init(&q,store,16u);CHECK(pnp_graph_inject(&q,0u,0u,&input)==PNP_OK);CHECK(pnp_graph_run(&g,&q,&out,(pnp_run_limits_t){5u,8u},&stats)==PNP_OK);CHECK(stats.steps==5u&&stats.queue_high_water==2u);CHECK(out.count==4u);CHECK(out.items[0].event.input_port==30u&&out.items[2].event.input_port==40u);CHECK(out.items[0].port==0u&&out.items[1].port==1u);return 0;
}
static int stable_edge_order(void){pnp_node_t n[3];pnp_state_domain_t d[3];pnp_edge_t e[4];pnp_graph_event_t store[8];pnp_queue_t q;pnp_graph_output_t items[2];pnp_graph_output_buffer_t out={items,2u,0u};pnp_run_stats_t stats;pnp_event_t input={0};pnp_graph_t g={n,3u,3u,e,4u,4u,d,3u,3u};memset(n,0,sizeof(n));memset(d,0,sizeof(d));for(uint32_t i=0u;i<3u;++i){n[i].config=pass_config(1u);n[i].state_domain=i;}e[0]=(pnp_edge_t){0u,0u,2u,22u};e[1]=(pnp_edge_t){0u,0u,1u,11u};e[2]=(pnp_edge_t){1u,0u,PNP_EXTERNAL_NODE,0u};e[3]=(pnp_edge_t){2u,0u,PNP_EXTERNAL_NODE,0u};pnp_queue_init(&q,store,8u);CHECK(pnp_graph_inject(&q,0u,0u,&input)==PNP_OK);CHECK(pnp_graph_run(&g,&q,&out,(pnp_run_limits_t){3u,4u},&stats)==PNP_OK);CHECK(out.count==2u&&out.items[0].event.input_port==22u&&out.items[1].event.input_port==11u);return 0;}
static int cycles_and_components(void){pnp_node_t n[4];pnp_state_domain_t d[4];pnp_edge_t e[4];pnp_graph_t g={n,4u,4u,e,2u,4u,d,4u,4u};pnp_graph_analysis_t a;memset(n,0,sizeof(n));memset(d,0,sizeof(d));for(uint32_t i=0u;i<4u;++i){n[i].config=pass_config(1u);n[i].state_domain=i;}e[0]=(pnp_edge_t){0u,0u,1u,0u};e[1]=(pnp_edge_t){1u,0u,0u,0u};CHECK(pnp_graph_analyze(&g,4u,&a)==PNP_OK&&a.has_cycles);g.edge_count=3u;e[1]=(pnp_edge_t){1u,0u,2u,0u};e[2]=(pnp_edge_t){2u,0u,0u,0u};CHECK(pnp_graph_analyze(&g,4u,&a)==PNP_OK&&a.has_cycles);g.edge_count=2u;e[0]=(pnp_edge_t){0u,0u,1u,0u};e[1]=(pnp_edge_t){2u,0u,3u,0u};CHECK(pnp_graph_analyze(&g,4u,&a)==PNP_OK&&!a.has_cycles);return 0;}
static int no_external_output(void){pnp_node_t n; pnp_state_domain_t d;pnp_graph_event_t store;pnp_queue_t q;pnp_run_stats_t stats;pnp_event_t input={0};pnp_graph_t g={&n,1u,1u,NULL,0u,0u,&d,1u,1u};memset(&n,0,sizeof(n));memset(&d,0,sizeof(d));n.config=pass_config(1u);pnp_queue_init(&q,&store,1u);CHECK(pnp_graph_inject(&q,0u,0u,&input)==PNP_OK);CHECK(pnp_graph_run(&g,&q,NULL,(pnp_run_limits_t){1u,0u},&stats)==PNP_OK&&stats.steps==1u);return 0;}
int main(void){CHECK(branch_and_diamond()==0);CHECK(stable_edge_order()==0);CHECK(cycles_and_components()==0);CHECK(no_external_output()==0);return 0;}
