#include "test_support.h"

static int direct_behaviors(void){
    pnp_config_t c;pnp_state_t s={{0}},next;pnp_event_t e={0};pnp_output_buffer_t o;
    c=pass_config(1u);CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.count==1u);c.emit_true=0u;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.count==0u);
    c=pass_config(0xffu);CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.count==8u);c=pass_config(1u);c.event_update_destination=(uint8_t)PNP_EVENT_DEST_TYPE;c.event_update_source=(uint8_t)PNP_EVENT_VALUE_CONSTANT;c.event_update_constant=10u;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.items[0].event.type==10u);c.event_update_destination=(uint8_t)PNP_EVENT_DEST_FLAGS;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.items[0].event.flags==10u);c.event_update_destination=(uint8_t)PNP_EVENT_DEST_SEQUENCE;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.items[0].event.sequence==10u);
    c=pass_config(1u);c.source_a.kind=(uint8_t)PNP_SRC_SEQUENCE;c.predicate=(uint8_t)PNP_PRED_EQ;c.predicate_invert=1u;c.compare_source.kind=(uint8_t)PNP_SRC_STATE_WORD;c.update_mode=(uint8_t)PNP_UPDATE_OPERAND_A;e.sequence=4u;s.words[0]=3u;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.count==1u&&next.words[0]==4u);s=next;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.count==0u);
    c=pass_config(1u);c.source_a.kind=(uint8_t)PNP_SRC_EVENT_FIELD;c.predicate=(uint8_t)PNP_PRED_LT_U;c.compare_source.kind=(uint8_t)PNP_SRC_CONSTANT;c.compare_source.immediate=10u;c.emit_false=2u;e.fields[0]=9u;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.items[0].port==0u);e.fields[0]=10u;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.items[0].port==1u);
    c=pass_config(1u);c.source_a.kind=(uint8_t)PNP_SRC_STATE_WORD;c.source_b.kind=(uint8_t)PNP_SRC_ONE;c.alu_op=(uint8_t)PNP_ALU_XOR;c.update_mode=(uint8_t)PNP_UPDATE_RESULT;s.words[0]=0u;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&next.words[0]==1u);
    c=pass_config(1u);c.source_a.kind=(uint8_t)PNP_SRC_STATE_WORD;c.predicate=(uint8_t)PNP_PRED_EQ;c.compare_source.kind=(uint8_t)PNP_SRC_ONE;c.emit_false=2u;s.words[0]=1u;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.items[0].port==0u);s.words[0]=0u;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.items[0].port==1u);
    c=pass_config(1u);c.source_a.kind=(uint8_t)PNP_SRC_STATE_WORD;c.source_b.kind=(uint8_t)PNP_SRC_ONE;c.alu_op=(uint8_t)PNP_ALU_ADD;c.predicate=(uint8_t)PNP_PRED_BIT_SET;c.predicate_bit=0u;c.update_mode=(uint8_t)PNP_UPDATE_RESULT;c.emit_false=2u;s.words[0]=0u;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.items[0].port==0u);s=next;CHECK(pnp_execute(&c,&s,&e,&next,&o)==PNP_OK&&o.items[0].port==1u);return 0;
}

static int epoch_counter(void){
    pnp_node_t n[3];pnp_state_domain_t d;pnp_edge_t edges[4];pnp_graph_event_t store[8];pnp_queue_t q;pnp_graph_output_t items[4];pnp_graph_output_buffer_t out={items,4u,0u};pnp_run_stats_t stats;pnp_event_t e={0};pnp_graph_t g={n,3u,3u,edges,4u,4u,&d,1u,1u};memset(n,0,sizeof(n));memset(&d,0,sizeof(d));
    n[0].config=pass_config(1u);n[0].config.source_a.kind=(uint8_t)PNP_SRC_EPOCH;n[0].config.predicate=(uint8_t)PNP_PRED_EQ;n[0].config.predicate_invert=1u;n[0].config.compare_source.kind=(uint8_t)PNP_SRC_STATE_WORD;n[0].config.emit_false=2u;
    n[1].config=pass_config(1u);n[1].config.source_a.kind=(uint8_t)PNP_SRC_EPOCH;n[1].config.update_mode=(uint8_t)PNP_UPDATE_RESULT;n[1].config.update_index=0u;n[1].config.event_update_destination=(uint8_t)PNP_EVENT_DEST_METADATA;n[1].config.event_update_source=(uint8_t)PNP_EVENT_VALUE_CONSTANT;n[1].config.event_update_constant=1u;
    n[2].config=pass_config(1u);n[2].config.source_a.kind=(uint8_t)PNP_SRC_STATE_WORD;n[2].config.source_a.index=1u;n[2].config.source_b.kind=(uint8_t)PNP_SRC_ONE;n[2].config.alu_op=(uint8_t)PNP_ALU_ADD;n[2].config.update_mode=(uint8_t)PNP_UPDATE_RESULT;n[2].config.update_index=1u;
    edges[0]=(pnp_edge_t){0u,0u,1u,0u};edges[1]=(pnp_edge_t){0u,1u,2u,0u};edges[2]=(pnp_edge_t){1u,0u,2u,0u};edges[3]=(pnp_edge_t){2u,0u,PNP_EXTERNAL_NODE,0u};e.epoch=7u;pnp_queue_init(&q,store,8u);CHECK(pnp_graph_inject(&q,0u,0u,&e)==PNP_OK);CHECK(pnp_graph_run(&g,&q,&out,(pnp_run_limits_t){3u,4u},&stats)==PNP_OK);CHECK(d.state.words[0]==7u&&d.state.words[1]==1u);pnp_queue_init(&q,store,8u);CHECK(pnp_graph_inject(&q,0u,0u,&e)==PNP_OK);CHECK(pnp_graph_run(&g,&q,&out,(pnp_run_limits_t){2u,3u},&stats)==PNP_OK);CHECK(d.state.words[1]==2u);return 0;
}

static int epoch_reset_regression(void){
    pnp_node_t n[4];pnp_state_domain_t d;pnp_edge_t edges[5];pnp_graph_event_t store[8];pnp_queue_t q;pnp_graph_output_t items[4];pnp_graph_output_buffer_t out={items,4u,0u};pnp_run_stats_t stats;pnp_event_t e={0};pnp_graph_t g={n,4u,4u,edges,5u,5u,&d,1u,1u};memset(n,0,sizeof(n));memset(&d,0,sizeof(d));
    n[0].config=pass_config(1u);n[0].config.source_a.kind=(uint8_t)PNP_SRC_EPOCH;n[0].config.predicate=(uint8_t)PNP_PRED_EQ;n[0].config.predicate_invert=1u;n[0].config.compare_source.kind=(uint8_t)PNP_SRC_STATE_WORD;n[0].config.emit_false=2u;
    n[1].config=pass_config(1u);n[1].config.source_a.kind=(uint8_t)PNP_SRC_EPOCH;n[1].config.update_mode=(uint8_t)PNP_UPDATE_RESULT;n[1].config.update_index=0u;n[2].config=pass_config(1u);n[2].config.update_mode=(uint8_t)PNP_UPDATE_CONSTANT;n[2].config.update_index=1u;n[2].config.update_constant=0u;
    n[3].config=pass_config(1u);n[3].config.source_a.kind=(uint8_t)PNP_SRC_STATE_WORD;n[3].config.source_a.index=1u;n[3].config.source_b.kind=(uint8_t)PNP_SRC_ONE;n[3].config.alu_op=(uint8_t)PNP_ALU_ADD;n[3].config.update_mode=(uint8_t)PNP_UPDATE_RESULT;n[3].config.update_index=1u;
    edges[0]=(pnp_edge_t){0u,0u,1u,0u};edges[1]=(pnp_edge_t){0u,1u,3u,0u};edges[2]=(pnp_edge_t){1u,0u,2u,0u};edges[3]=(pnp_edge_t){2u,0u,3u,0u};edges[4]=(pnp_edge_t){3u,0u,PNP_EXTERNAL_NODE,0u};
    e.epoch=7u;pnp_queue_init(&q,store,8u);CHECK(pnp_graph_inject(&q,0u,0u,&e)==PNP_OK);CHECK(pnp_graph_run(&g,&q,&out,(pnp_run_limits_t){4u,5u},&stats)==PNP_OK);CHECK(d.state.words[0]==7u&&d.state.words[1]==1u);pnp_queue_init(&q,store,8u);CHECK(pnp_graph_inject(&q,0u,0u,&e)==PNP_OK);CHECK(pnp_graph_run(&g,&q,&out,(pnp_run_limits_t){2u,3u},&stats)==PNP_OK);CHECK(d.state.words[1]==2u);e.epoch=8u;pnp_queue_init(&q,store,8u);CHECK(pnp_graph_inject(&q,0u,0u,&e)==PNP_OK);CHECK(pnp_graph_run(&g,&q,&out,(pnp_run_limits_t){4u,5u},&stats)==PNP_OK);CHECK(d.state.words[0]==8u&&d.state.words[1]==1u);return 0;
}

int main(void){CHECK(direct_behaviors()==0);CHECK(epoch_counter()==0);CHECK(epoch_reset_regression()==0);return 0;}
